#ifndef CRIO_IO_MAP_H
#define CRIO_IO_MAP_H

#define LEFT_DRIVE_MOTOR 1
#define RIGHT_DRIVE_MOTOR 2
#define LEFT_DRIVE_ENCODER_A 1
#define LEFT_DRIVE_ENCODER_B 2
#define RIGHT_DRIVE_ENCODER_A 3
#define RIGHT_DRIVE_ENCODER_B 4
#define LEFT_DRIVE_SOLENOID 1
#define RIGHT_DRIVE_SOLENOID 2

#endif
