#ifndef ROBOTPARAMETERS_H
#define ROBOTPARAMETERS_H
#define M_PI 3.14159265358979323846
#define ROBOTLENGTH 10
#define ROBOTWIDTH 10
#define ENCODER_OFFSET_FILENAME "Encoder_Offsets"
#define LOADED_SHOOTER_POSITION 0
#define WINCH_TOLERANCE .1
#define DISTANCE_PER_VOLT 20

#define INCHES_TO_POT_VOLTS .122

#define TRUSS_SHOT_DISTANCE		5
#define OUTLET_SHOT_DISTANCE	5
#define CORNER_SHOT_DISTANCE	5

#endif
